name: CRM CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      # 1. Build Stage
      - name: Build - Install Dependencies
        run: |
          pip install -r requirements.txt
      
      # 2. Test Stage
      - name: Test - Run Pytest
        run: |
          pytest
          
      # 3. Coverage Stage
      - name: Coverage - Run Pytest-Cov
        run: |
          pytest --cov=app --cov-report=xml --cov-fail-under=75
        # [cite_start]This command will FAIL the pipeline if coverage is < 75% [cite: 628]
          
      # 4. Lint Stage
      - name: Lint - Run Pylint
        run: |
          pylint app.py --fail-under=7.5
        # [cite_start]This command will FAIL the pipeline if score is < 7.5 [cite: 676]

      # 5. Security Stage
      - name: Security - Run Bandit
        run: |
          bandit -r app.py -l --fail-on-issue
        # This fails on any Low-level issue or higher