name: CRM CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Create Firebase Service Account Key
        # This step takes the secret and writes it to the file
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > serviceAccountKey.json
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}

      - name: Build - Install Dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Test - Run Pytest
        run: |
          pytest
          
      - name: Coverage - Run Pytest-Cov
        run: |
          pytest --cov=app --cov-report=xml --cov-fail-under=75
          
      - name: Lint - Run Pylint
        run: |
          pylint app.py --fail-under=7.5

      - name: Security - Run Bandit
        run: |
          bandit -r app.py -l --fail-on-issue